/* https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

export const problem2 = () => {
  let firstNum = 1;
  let secondNum = 1;
  let evenValuedSums = 0;
  do {
    const fibonacci = firstNum + secondNum;
    if (fibonacci % 2 === 0) {
      evenValuedSums += fibonacci;
    }
    const temp = firstNum;
    firstNum = secondNum;
    secondNum = secondNum + temp;
  } while (secondNum < 4000000);

  return evenValuedSums;
};
